In [18]:
from src.Matrices import SymTri, Givens
from src.testing import test_decomposition, test_eigen, test_multiplication
import numpy as np

## NM HW1: QR razcep simetrične tridiagonalne matrike
V direktoriju src/Matrices.py sta definirana razreda SymTri, ki predstavlja simetrično tridiagonalno matriko, ter razred Givens, ki predstavlja rotacijsko matriko. Vse metode so dokumentirane.
V prihodnjih vrsticah so postavljene metode testiranja, *n* prestavlja število posameznih iteracij, medtem ko *drange* predstavlja vrednosti katere lahko vzame dimenzija matrike.

In [19]:
test_multiplication(n=100,drange=(10,25))

True


In [20]:
test_decomposition(n=100,drange=(10,25))

True


In [21]:
test_eigen(n=100,drange=(10,25))

True


### Primer:
Spodaj je 'pipeline' postopka kako matriko definiramo in nakoncu izračunamo njene lastne vrednosti. Iz primera iz wikipedije:https://en.wikipedia.org/wiki/Givens_rotation#Triangularization

In [22]:
#Definiramo matriko
A = SymTri([6,1,3],[5,4])

In [23]:
A.elements

array([[6, 5, 0],
       [5, 1, 4],
       [0, 4, 3]])

In [24]:
#Izračunamo QR razcep
Q, R = A.qr()

In [26]:
with np.printoptions(precision=2, suppress=True):
    print(Q)
    print(R)

[[ 0.77 -0.33 -0.55]
 [ 0.64  0.4   0.66]
 [ 0.   -0.85  0.52]]
[[ 7.81  4.48  2.56]
 [ 0.   -4.68 -0.97]
 [ 0.    0.    4.18]]


In [27]:
#Kandati lastnih vrednosti so diagonalni elementi matrike R, tukaj začnemo QR iteracijo kjer gledamo, kdaj bo stvar konvergirala:

In [28]:
A_new = R @ Q

In [29]:
with np.printoptions(precision=2, suppress=True):
    print(A_new)

[[ 8.87 -3.    0.  ]
 [-3.   -1.04 -3.58]
 [ 0.   -3.58  2.17]]


In [31]:
#Na novodobljeni matriki (ki je tudi SymTri!) tako spet naredimo QR razcep
A_new = SymTri(A_new.diagonal(),A_new.diagonal(offset=1))
Q_new, R_new = A_new.qr()

In [32]:
with np.printoptions(precision=2, suppress=True):
    print(Q_new)
    print(R_new)

[[ 0.95  0.15 -0.28]
 [-0.32  0.45 -0.83]
 [ 0.    0.88  0.48]]
[[ 9.36 -2.51  1.14]
 [ 0.   -4.07  0.29]
 [ 0.    0.    4.01]]


In [34]:
#Po nekaj takih iteracijah...
eigenl, eigenv = A.eigen() 

In [37]:
with np.printoptions(precision=2, suppress=True):
    print(eigenl)

[ 9.84  4.02 -3.87]


In [39]:
np.linalg.eig(A.elements)[0]

array([-3.86492147,  9.84316153,  4.02175994])

In [ ]:
#Kar lahko vidimo da se ujema